version: '3.9'

services:
  casablanca_postgres:
    container_name: casablanca_postgres
    image: postgres:15.1-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret}
    ports:
      - "5432:5432"