// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: academic_calendar_event.sql

package db

import (
	"context"
	"time"
)

const createAcademicCalendarEvent = `-- name: CreateAcademicCalendarEvent :one
INSERT INTO "academic_calendar_event" (
    "academic_year_id", "name", "type", "start_date", "end_date"
) VALUES(
    $1, $2, $3, $4, $5
) RETURNING id, academic_year_id, name, type, start_date, end_date, created_at
`

type CreateAcademicCalendarEventParams struct {
	AcademicYearID int64     `json:"academic_year_id"`
	Name           string    `json:"name"`
	Type           string    `json:"type"`
	StartDate      time.Time `json:"start_date"`
	EndDate        time.Time `json:"end_date"`
}

func (q *Queries) CreateAcademicCalendarEvent(ctx context.Context, arg CreateAcademicCalendarEventParams) (AcademicCalendarEvent, error) {
	row := q.db.QueryRow(ctx, createAcademicCalendarEvent,
		arg.AcademicYearID,
		arg.Name,
		arg.Type,
		arg.StartDate,
		arg.EndDate,
	)
	var i AcademicCalendarEvent
	err := row.Scan(
		&i.ID,
		&i.AcademicYearID,
		&i.Name,
		&i.Type,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
	)
	return i, err
}

type CreateAcademicCalendarEventsParams struct {
	AcademicYearID int64     `json:"academic_year_id"`
	Name           string    `json:"name"`
	Type           string    `json:"type"`
	StartDate      time.Time `json:"start_date"`
	EndDate        time.Time `json:"end_date"`
}
