// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"database/sql"
	"time"
)

type Permission struct {
	ID             int64     `json:"id"`
	PermissionName string    `json:"permission_name"`
	Description    string    `json:"description"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type Role struct {
	ID          int64     `json:"id"`
	RoleName    string    `json:"role_name"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type RolePermission struct {
	RoleID       sql.NullInt64 `json:"role_id"`
	PermissionID sql.NullInt64 `json:"permission_id"`
	CreatedAt    time.Time     `json:"created_at"`
	UpdatedAt    time.Time     `json:"updated_at"`
}

type User struct {
	ID             int64         `json:"id"`
	Username       string        `json:"username"`
	HashedPassword string        `json:"hashed_password"`
	RoleID         sql.NullInt64 `json:"role_id"`
	CreatedAt      time.Time     `json:"created_at"`
	UpdatedAt      time.Time     `json:"updated_at"`
}
