apiVersion: apps/v1
kind: Deployment
metadata:
  name: vincpr-api-deployment
  labels:
    app: vincpr-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vincpr-api
  template:
    metadata:
      labels:
        app: vincpr-api
    spec:
      containers:
        - name: vincpr-api
          image: 095420225348.dkr.ecr.eu-west-1.amazonaws.com/simplebank:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080