// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/academic_year": {
            "post": {
                "description": "create new academic year",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AcademicCalendar"
                ],
                "summary": "create new academic year",
                "parameters": [
                    {
                        "description": "input required: academic year name, start date, end date",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github.com_VinCPR_backend_api.createAcademicYearRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "$ref": "#/definitions/github.com_VinCPR_backend_api.academicYearResponse"
                        }
                    }
                }
            }
        },
        "/academic_year/calendar": {
            "get": {
                "description": "return the list of events of an academic year",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AcademicCalendar"
                ],
                "summary": "return the list of events of an academic year",
                "parameters": [
                    {
                        "type": "string",
                        "description": "academic year name",
                        "name": "academicYearName",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github.com_VinCPR_backend_api.getAcademicCalendarResponse"
                            }
                        }
                    }
                }
            }
        },
        "/academic_year/list": {
            "get": {
                "description": "list created academic year",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "AcademicCalendar"
                ],
                "summary": "list created academic year",
                "parameters": [
                    {
                        "type": "string",
                        "description": "page number",
                        "name": "pageNumber",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "page size",
                        "name": "pageSize",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github.com_VinCPR_backend_api.academicYearResponse"
                            }
                        }
                    }
                }
            }
        },
        "/attending": {
            "post": {
                "description": "create new Attending",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Attending"
                ],
                "summary": "create new Attending",
                "parameters": [
                    {
                        "description": "input required: attending user_id, firstname, lastname, mobile",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github.com_VinCPR_backend_api.createAttendingRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "$ref": "#/definitions/github.com_VinCPR_backend_api.AttendingResponse"
                        }
                    }
                }
            }
        },
        "/block/list": {
            "get": {
                "description": "list blocks in that academic year",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Blocks"
                ],
                "summary": "list blocks in that academic year",
                "parameters": [
                    {
                        "type": "string",
                        "description": "academic year name",
                        "name": "academicYearName",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github.com_VinCPR_backend_api.blockResponse"
                            }
                        }
                    }
                }
            }
        },
        "/group/list": {
            "get": {
                "description": "list groups in that academic year",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Groups"
                ],
                "summary": "list groups in that academic year",
                "parameters": [
                    {
                        "type": "string",
                        "description": "academic year name",
                        "name": "academicYearName",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github.com_VinCPR_backend_api.groupResponse"
                            }
                        }
                    }
                }
            }
        },
        "/hospital": {
            "post": {
                "description": "create new hospital",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Hospital"
                ],
                "summary": "create new hospital",
                "parameters": [
                    {
                        "description": "input required: hospital name, description, address",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github.com_VinCPR_backend_api.createHospitalRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "$ref": "#/definitions/github.com_VinCPR_backend_api.HospitalResponse"
                        }
                    }
                }
            }
        },
        "/period/list": {
            "get": {
                "description": "list periods in that academic year",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Periods"
                ],
                "summary": "list periods in that academic year",
                "parameters": [
                    {
                        "type": "string",
                        "description": "academic year name",
                        "name": "academicYearName",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github.com_VinCPR_backend_api.periodResponse"
                            }
                        }
                    }
                }
            }
        },
        "/service": {
            "post": {
                "description": "create new service",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Service"
                ],
                "summary": "create new service",
                "parameters": [
                    {
                        "description": "input required: service hospitalID, specialtyID, name, description",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github.com_VinCPR_backend_api.createServiceRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "$ref": "#/definitions/github.com_VinCPR_backend_api.serviceResponse"
                        }
                    }
                }
            }
        },
        "/service/list/hospital": {
            "get": {
                "description": "list created service",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Services"
                ],
                "summary": "list created service",
                "parameters": [
                    {
                        "type": "string",
                        "description": "page number",
                        "name": "pageNumber",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "page size",
                        "name": "pageSize",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github.com_VinCPR_backend_api.serviceResponse"
                            }
                        }
                    }
                }
            }
        },
        "/service/list/specialty": {
            "get": {
                "description": "list created service",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Services"
                ],
                "summary": "list created service",
                "parameters": [
                    {
                        "type": "string",
                        "description": "page number",
                        "name": "pageNumber",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "page size",
                        "name": "pageSize",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github.com_VinCPR_backend_api.serviceResponse"
                            }
                        }
                    }
                }
            }
        },
        "/service/list/specialty_and_hospital": {
            "get": {
                "description": "list created service",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Services"
                ],
                "summary": "list created service",
                "parameters": [
                    {
                        "type": "string",
                        "description": "page number",
                        "name": "pageNumber",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "page size",
                        "name": "pageSize",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github.com_VinCPR_backend_api.serviceResponse"
                            }
                        }
                    }
                }
            }
        },
        "/servicetoattending": {
            "post": {
                "description": "create new service to attending",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ServiceToAttending"
                ],
                "summary": "create new service to attending",
                "parameters": [
                    {
                        "description": "input required: serviceID, attendingID",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github.com_VinCPR_backend_api.createServiceToAttendingRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "$ref": "#/definitions/github.com_VinCPR_backend_api.ServiceToAttendingResponse"
                        }
                    }
                }
            }
        },
        "/specialty": {
            "post": {
                "description": "create new specialty",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Specialty"
                ],
                "summary": "create new specialty",
                "parameters": [
                    {
                        "description": "input required: specialty name, description, address",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github.com_VinCPR_backend_api.createSpecialtyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "$ref": "#/definitions/github.com_VinCPR_backend_api.SpecialtyResponse"
                        }
                    }
                }
            }
        },
        "/student": {
            "post": {
                "description": "create new student",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Student"
                ],
                "summary": "create new student",
                "parameters": [
                    {
                        "description": "input required: student user_id, student_id, firstname, lastname, mobile",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github.com_VinCPR_backend_api.createStudentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "$ref": "#/definitions/github.com_VinCPR_backend_api.StudentResponse"
                        }
                    }
                }
            }
        },
        "/users": {
            "post": {
                "description": "upsert wallet address",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "upsert new user",
                "parameters": [
                    {
                        "description": "create new user request requires username, password, and role",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github.com_VinCPR_backend_api.createUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "$ref": "#/definitions/github.com_VinCPR_backend_api.userResponse"
                        }
                    }
                }
            }
        },
        "/users/login": {
            "post": {
                "description": "upsert wallet address",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "upsert new user",
                "parameters": [
                    {
                        "description": "login request requires username, password",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github.com_VinCPR_backend_api.loginUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "$ref": "#/definitions/github.com_VinCPR_backend_api.loginUserResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.ServiceToAttendingResponse": {
            "type": "object",
            "properties": {
                "attending_id": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "service_id": {
                    "type": "integer"
                }
            }
        },
        "api.SpecialtyResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "api.StudentResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "mobile": {
                    "type": "string"
                },
                "student_id": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "api.academicCalendarEventResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "end_date": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "start_date": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "api.academicYearResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "end_date": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "start_date": {
                    "type": "string"
                }
            }
        },
        "api.blockResponse": {
            "type": "object",
            "properties": {
                "academic_year_id": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "period": {
                    "type": "integer"
                }
            }
        },
        "api.createAcademicYearRequest": {
            "type": "object",
            "required": [
                "end_date",
                "name",
                "start_date"
            ],
            "properties": {
                "end_date": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "start_date": {
                    "type": "string"
                }
            }
        },
        "api.createServiceToAttendingRequest": {
            "type": "object",
            "required": [
                "attending_id",
                "service_id"
            ],
            "properties": {
                "attending_id": {
                    "type": "integer"
                },
                "service_id": {
                    "type": "integer"
                }
            }
        },
        "api.createSpecialtyRequest": {
            "type": "object",
            "required": [
                "description",
                "name"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "api.createStudentRequest": {
            "type": "object",
            "required": [
                "firstname",
                "lastname",
                "mobile",
                "student_id",
                "user_id"
            ],
            "properties": {
                "firstname": {
                    "type": "string"
                },
                "lastname": {
                    "type": "string"
                },
                "mobile": {
                    "type": "string"
                },
                "student_id": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "api.createUserRequest": {
            "type": "object",
            "required": [
                "email",
                "password",
                "role_name"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 8
                },
                "role_name": {
                    "type": "string"
                }
            }
        },
        "api.getAcademicCalendarResponse": {
            "type": "object",
            "properties": {
                "academic_calendar_events": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.academicCalendarEventResponse"
                    }
                },
                "academic_year": {
                    "$ref": "#/definitions/api.academicYearResponse"
                }
            }
        },
        "api.groupResponse": {
            "type": "object",
            "properties": {
                "academic_year_id": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "api.loginUserRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 8
                }
            }
        },
        "api.loginUserResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "access_token_expires_at": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                },
                "refresh_token_expires_at": {
                    "type": "string"
                },
                "session_id": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/api.userResponse"
                }
            }
        },
        "api.periodResponse": {
            "type": "object",
            "properties": {
                "academic_year_id": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "end_date": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "start_date": {
                    "type": "string"
                }
            }
        },
        "api.userResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "role_name": {
                    "type": "string"
                }
            }
        },
        "github.com_VinCPR_backend_api.AttendingResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "mobile": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "github.com_VinCPR_backend_api.HospitalResponse": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "github.com_VinCPR_backend_api.ServiceToAttendingResponse": {
            "type": "object",
            "properties": {
                "attending_id": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "service_id": {
                    "type": "integer"
                }
            }
        },
        "github.com_VinCPR_backend_api.SpecialtyResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "github.com_VinCPR_backend_api.StudentResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "mobile": {
                    "type": "string"
                },
                "student_id": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "github.com_VinCPR_backend_api.academicCalendarEventResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "end_date": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "start_date": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "github.com_VinCPR_backend_api.academicYearResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "end_date": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "start_date": {
                    "type": "string"
                }
            }
        },
        "github.com_VinCPR_backend_api.blockResponse": {
            "type": "object",
            "properties": {
                "academic_year_id": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "period": {
                    "type": "integer"
                }
            }
        },
        "github.com_VinCPR_backend_api.createAcademicYearRequest": {
            "type": "object",
            "required": [
                "end_date",
                "name",
                "start_date"
            ],
            "properties": {
                "end_date": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "start_date": {
                    "type": "string"
                }
            }
        },
        "github.com_VinCPR_backend_api.createAttendingRequest": {
            "type": "object",
            "required": [
                "firstname",
                "lastname",
                "mobile",
                "user_id"
            ],
            "properties": {
                "firstname": {
                    "type": "string"
                },
                "lastname": {
                    "type": "string"
                },
                "mobile": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "github.com_VinCPR_backend_api.createHospitalRequest": {
            "type": "object",
            "required": [
                "address",
                "description",
                "name"
            ],
            "properties": {
                "address": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "github.com_VinCPR_backend_api.createServiceRequest": {
            "type": "object",
            "required": [
                "description",
                "hospital",
                "name",
                "specialty"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "hospital": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "specialty": {
                    "type": "string"
                }
            }
        },
        "github.com_VinCPR_backend_api.createServiceToAttendingRequest": {
            "type": "object",
            "required": [
                "attending_id",
                "service_id"
            ],
            "properties": {
                "attending_id": {
                    "type": "integer"
                },
                "service_id": {
                    "type": "integer"
                }
            }
        },
        "github.com_VinCPR_backend_api.createSpecialtyRequest": {
            "type": "object",
            "required": [
                "description",
                "name"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "github.com_VinCPR_backend_api.createStudentRequest": {
            "type": "object",
            "required": [
                "firstname",
                "lastname",
                "mobile",
                "student_id",
                "user_id"
            ],
            "properties": {
                "firstname": {
                    "type": "string"
                },
                "lastname": {
                    "type": "string"
                },
                "mobile": {
                    "type": "string"
                },
                "student_id": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "github.com_VinCPR_backend_api.createUserRequest": {
            "type": "object",
            "required": [
                "email",
                "password",
                "role_name"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 8
                },
                "role_name": {
                    "type": "string"
                }
            }
        },
        "github.com_VinCPR_backend_api.getAcademicCalendarResponse": {
            "type": "object",
            "properties": {
                "academic_calendar_events": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github.com_VinCPR_backend_api.academicCalendarEventResponse"
                    }
                },
                "academic_year": {
                    "$ref": "#/definitions/github.com_VinCPR_backend_api.academicYearResponse"
                }
            }
        },
        "github.com_VinCPR_backend_api.groupResponse": {
            "type": "object",
            "properties": {
                "academic_year_id": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "github.com_VinCPR_backend_api.loginUserRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "maxLength": 64,
                    "minLength": 8
                }
            }
        },
        "github.com_VinCPR_backend_api.loginUserResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "access_token_expires_at": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                },
                "refresh_token_expires_at": {
                    "type": "string"
                },
                "session_id": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/github.com_VinCPR_backend_api.userResponse"
                }
            }
        },
        "github.com_VinCPR_backend_api.periodResponse": {
            "type": "object",
            "properties": {
                "academic_year_id": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "end_date": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "start_date": {
                    "type": "string"
                }
            }
        },
        "github.com_VinCPR_backend_api.serviceResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "hospital": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "specialty": {
                    "type": "string"
                }
            }
        },
        "github.com_VinCPR_backend_api.userResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "role_name": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
