definitions:
  github.com_VinCPR_backend_api.createAcademicYearRequest:
    properties:
      endDate:
        type: string
      name:
        type: string
      startDate:
        type: string
    required:
    - endDate
    - name
    - startDate
    type: object
  github.com_VinCPR_backend_api.createAcademicYearResponse:
    properties:
      createdAt:
        type: string
      endDate:
        type: string
      name:
        type: string
      startDate:
        type: string
    type: object
  github.com_VinCPR_backend_api.createUserRequest:
    properties:
      email:
        type: string
      password:
        maxLength: 64
        minLength: 8
        type: string
      role_name:
        type: string
    required:
    - email
    - password
    - role_name
    type: object
  github.com_VinCPR_backend_api.loginUserRequest:
    properties:
      email:
        type: string
      password:
        maxLength: 64
        minLength: 8
        type: string
    required:
    - email
    - password
    type: object
  github.com_VinCPR_backend_api.loginUserResponse:
    properties:
      access_token:
        type: string
      access_token_expires_at:
        type: string
      refresh_token:
        type: string
      refresh_token_expires_at:
        type: string
      session_id:
        type: string
      user:
        $ref: '#/definitions/github.com_VinCPR_backend_api.userResponse'
    type: object
  github.com_VinCPR_backend_api.userResponse:
    properties:
      created_at:
        type: string
      email:
        type: string
      role_name:
        type: string
    type: object
info:
  contact: {}
paths:
  /academic_year:
    post:
      consumes:
      - application/json
      description: create new academic year
      parameters:
      - description: input requires academic year name, start date, end date
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/github.com_VinCPR_backend_api.createAcademicYearRequest'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/github.com_VinCPR_backend_api.createAcademicYearResponse'
      summary: create new academic year
      tags:
      - AcademicCalendar
  /users:
    post:
      consumes:
      - application/json
      description: upsert wallet address
      parameters:
      - description: create new user request requires username, password, and role
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/github.com_VinCPR_backend_api.createUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/github.com_VinCPR_backend_api.userResponse'
      summary: upsert new user
      tags:
      - Authentication
  /users/login:
    post:
      consumes:
      - application/json
      description: upsert wallet address
      parameters:
      - description: login request requires username, password
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/github.com_VinCPR_backend_api.loginUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/github.com_VinCPR_backend_api.loginUserResponse'
      summary: upsert new user
      tags:
      - Authentication
swagger: "2.0"
